server:
  port: 8082

spring:
  application:
    name: service-b
  datasource:
    url: jdbc:postgresql://localhost:5432/service_b
    username: postgres
    password: ndtdoanh
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: service-b-activity
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: RECORD

app:
  kafka:
    product-updates-topic: product.updates
