server:
  port: 8080

spring:
  application:
    name: service-a
  datasource:
    url: jdbc:postgresql://localhost:5432/service_a
    username: ndtdoanh
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    product-updates-topic: product.updates
